---
title: "STA 304 A1 Q3"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## R Markdown
a)
```{r }
student_number <- (c(1,0,0,4,7,8,4,6,4,6))
tibble(
'Mean' = mean(student_number),
'Median' = median(student_number),
'Variance' = var(student_number)*9/10,
'Sum' = sum(student_number),
'Proportion' = sum(student_number == student_number[1])/length(student_number))
```
b)
```{r }
hist(student_number, xlab = 'Digit',  main='Histogram for Digits of UofT Student Number #1004784646', breaks = 12)
axis(1, at=1:9)
```
c)
```{r }
hist(combn(student_number, 3, mean), xlab = 'Sample Mean Based on Drawing samples of Size 3 without Replacement',main = 'Histogram of Sample Mean #1004784646')
```
d)
```{r }
N = choose(10, 3)
tibble(
'Mean' = mean(combn(student_number, 3, mean)),
'Variance' = round(((var(combn(student_number, 3, mean)) * (N-1))/N), digits = 2))
```
e)
```{r }
set.seed(1004784646)
hbar = rep(0,250000)
for(i in 1:250000){hbar[i]=mean(sample(student_number, 3, replace = TRUE))}
hist(hbar, xlab = 'Sample Mean Based on Drawing samples of Size 3 with Replacement', main = 'Histogram of Sample Mean #1004784646')
```
f)
```{r }
tibble(
'Mean' = round(mean(hbar), digits = 3), 
'Variance' = round(var(hbar), digits = 3))
'abc'
```



